#
# Conditional build:
%bcond_without	tests		# do not perform "make test"
#
%include	/usr/lib/rpm/macros.perl
%define	pdir	Nmap
%define	pnam	Parser
Summary:	Nmap::Parser - parse nmap scan data with perl
Summary(pl.UTF-8):	Nmap::Parser - parsowanie danych ze skanowania nmapem
Name:		perl-Nmap-Parser
Version:	1.12
Release:	1
License:	GPL v2+
Group:		Development/Languages/Perl
Source0:	http://www.cpan.org/modules/by-module/%{pdir}/%{pdir}-%{pnam}-%{version}.tar.gz
# Source0-md5:	ea2732f02f34dda18a89018c57af040d
URL:		http://search.cpan.org/dist/Nmap-Parser/
BuildRequires:	perl-devel >= 1:5.8.0
BuildRequires:	rpm-perlprov >= 4.1-13
%if %{with tests}
BuildRequires:	perl-XML-Twig >= 3.16
%endif
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
This module implements a interface to the information contained in an
nmap scan. It is implemented by parsing the xml scan data that is
generated by nmap. This will enable anyone who utilizes nmap to
quickly create fast and robust security scripts that utilize the
powerful port scanning abilities of nmap.

%description -l pl.UTF-8
Moduł ten to implementacja interfejsu do informacji zebranych podczas
skanowania nmapem. Działa na zasadzie przetwarzania danych XML
wygenerowanych przez program nmap. Pozwala to na generowanie szybkich
i złożonych skryptów korzystających z potężnych możliwości, jakie daje
program nmap.

%prep
%setup -q -n %{pdir}-%{pnam}-%{version}

%build
%{__perl} Makefile.PL \
	INSTALLDIRS=vendor
%{__make}

%{?with_tests:%{__make} test}

%install
rm -rf $RPM_BUILD_ROOT

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc Changes README
%dir %{perl_vendorlib}/Nmap
%{perl_vendorlib}/Nmap/*.pm
%{_mandir}/man3/*
